# -*- coding: utf-8 -*-
"""CountServer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zFTdQor9VHXVLO7tOiz_02itqR26z9zd
"""

pip install flask flask-cors opencv-python-headless numpy ultralytics pillow pyngrok

!ngrok authtoken '''Insert your Authentication Token'''

import cv2
import base64
import numpy as np
from PIL import Image
from pyngrok import ngrok
from flask_cors import CORS
from ultralytics import YOLO
from flask import Flask, request, jsonify

app = Flask(__name__)
CORS(app)

model = YOLO('yolov8m.pt')

def process_with_yolov8(image):
    results = model(image)
    detections = results[0].boxes.data.cpu().numpy()
    class_dict = results[0].names
    person_class_index = [key for key, value in class_dict.items() if value == 'person'][0]
    person_detections = [d for d in detections if int(d[5]) == person_class_index]
    people_count = len(person_detections)

    return people_count

@app.route('/')
def home():
    return "Welcome to the Crowd Detection API"

@app.route('/favicon.ico')
def favicon():
    return '', 204

@app.route('/detect', methods=['POST'])
def detect_people():
    file = request.files['image']
    img = Image.open(file.stream).convert('RGB')
    img = np.array(img)
    people_count = process_with_yolov8(img)
    return jsonify({'people_count': people_count})

if __name__ == '__main__':
    public_url = ngrok.connect(5000)
    print(f"Public URL: {public_url}")
    app.run(host='0.0.0.0', port=5000)